### PR TITLE
Contributing.md

### PR DESCRIPTION
**Pull request by codebreaker3008**
Added the file Contributing.md

### CODE REVIEW

**Comment by Yeasir0032** [comment]
Good work
Can you just reference this file in Readme.md
Saying like read about how to contribute or contribute guidelines

**Comment by Yeasir0032** [comment]
Update the PR after this

**Comment by codebreaker3008** [comment]
> Update the PR after this

OK will do that

**Comment by codebreaker3008** [comment]
I have updated the PR. could you verify it ?

**Pull request merged**
