### PR TITLE
Added the feature to auto comment on pr merged 

### LINKED ISSUE #57: Auto Commenting when a PR is merged
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
## Related Issue
Fixes #57 

## Description
I have added auto-comment-on-pr-merge.yml in .github/workflows directory. This file will add the feature of auto commenting when a pr is merged.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Yeasir0032** [comment]
#### You can have these messages too
Thank you for your valuable contribution! Your changes are now part of the main branch and will be included in the next release.
If you haven't done so already, consider starring our repository! Starring helps to bookmark the repository for easy access and shows your support and appreciation.

**Comment by suhanipaliwal** [comment]
> #### You can have these messages too
> Thank you for your valuable contribution! Your changes are now part of the main branch and will be included in the next release. If you haven't done so already, consider starring our repository! Starring helps to bookmark the repository for easy access and shows your support and appreciation.

Added these messages as well.

**Comment by Yeasir0032** [comment]
Good work.
Your PR will be merged shortly.

Why you have created duplicate PR in pr number 78

**Comment by suhanipaliwal** [comment]
> Good work. Your PR will be merged shortly.
> 
> Why you have created duplicate PR in pr number 78

That is not a duplicate pr. It has a different purpose. Pr 78 is adding the feature of auto commenting on a new pull request being made. But this pr is adding the feature of auto commenting after a pull request is approved and merged by the admins.

**Comment by suhanipaliwal** [comment]
Please add the label of level1 on this pr

**Comment by suhanipaliwal** [comment]
Could you please add the label of level1

**Pull request merged**
