### PR TITLE
added register form

### PR DESCRIPTION
**Pull request by mahek0620**

### CODE REVIEW

**Comment by Yeasir0032** [comment]
Your dark and light mode are not according to best practices used in the project. 
Please check different Components, how they have used dark mode and light mode.

**Comment by mahek0620** [comment]
@Yeasir0032 can you check updated register.tsx

**Review by Yeasir0032 — CHANGES_REQUESTED** [review]
Something more you have to change 
 - Remove the Theme toggle button as there is a global toggle.
 - Remove unnecessary use of next themes.

**Comment by Yeasir0032** [comment]
You should follow Pull Request Format - Adding the issue reference, Ticking some textboxes.

**Comment by mahek0620** [comment]
Related Issue
Fixes #65

Description
Removed the Theme toggle button as there is a global toggle.
Removed unnecessary use of next themes.

Type of PR
 Bug fix
[ X] Feature enhancement
 Documentation update
 Other (specify): _______________
Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

Checklist:
 I have performed a self-review of my code
[ X] I have read and followed the Contribution Guidelines.
[X ] I have tested the changes thoroughly before submitting this pull request.
[X ] I have commented my code, particularly in hard-to-understand areas.

**Comment by mahek0620** [comment]
@Yeasir0032 can you please check the updated register form

**Comment by mahek0620** [comment]
@Yeasir0032 can you please add labels

**Comment by mahek0620** [comment]
@Yeasir0032 can you please add labels

**Comment by mahek0620** [comment]
@Yeasir0032 kindly add labels to it

**Comment by mahek0620** [comment]
@Yeasir0032 please review it

**Comment by mahek0620** [comment]
@PayalKumari10 can you review it

**Comment by mahek0620** [comment]
@Yeasir0032 can you review it the change which you requested has been modified

**Review by Yeasir0032 — APPROVED** [review]

**Pull request merged**
