### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alishasingh06**
removed grammatical errors

### CODE REVIEW

**Comment by Yeasir0032** [comment]
You should have created an issue first so that I can assign Levels to it.

**Comment by Yeasir0032** [comment]
Okay I will merge it anyway

**Comment by Yeasir0032** [comment]
Hey @alishasingh06 can you update the readme to add the deployed link [https://discord-a.up.railway.app/](https://discord-a.up.railway.app/).

**Comment by Yeasir0032** [comment]
There are some more typing errors in the readme.md file check [this section](https://github.com/Yeasir0032/Discord-Clone?tab=readme-ov-file#fork-the-repo). One more thing you can do you can give the text to chatgpt to scan for mistakes.

**Comment by alishasingh06** [comment]
> Hey @alishasingh06 can you update the readme to add the deployed link https://discord-a.up.railway.app/.

done sir

**Pull request merged**
