### PR TITLE
chore: remove .vscode

### PR DESCRIPTION
**Pull request by 01Sriharsha**
- removed .vscode directory

### CODE REVIEW

**Comment by Yeasir0032** [comment]
Delete the whole .vscode folder

**Comment by 01Sriharsha** [comment]
Okay!

**Comment by Yeasir0032** [comment]
Where @01Sriharsha I cannot see in the pull request?
Make sure you updated the pull request

**Comment by 01Sriharsha** [comment]
image


> Where @01Sriharsha I cannot see in the pull request? Make sure you updated the pull request

I have correctly made a PR! Its visible to me

**Comment by 01Sriharsha** [comment]
@Yeasir0032  Yes, It's reflecting and on the next clone or push, It wont be shown

**Comment by Yeasir0032** [comment]
Okay 
Let's take the step

**Comment by Yeasir0032** [comment]
Did you referenced the issue in the pr?

**Pull request merged**
