### PR TITLE
feat: add codeql workflow for typescript

### PR DESCRIPTION
**Pull request by harmeetsingh11**
## Issue that this pull request solves

 Closes: #87 

### Files added
- `.github/workflows/codeql.yml`

### To run this workflow you need to enable the following permission:

1. **Go to your project repository settings**
2. **On left pane > Actions > General**

image

3. **Scroll down and Go to Workflow permissions > select "Read and write permissions"**

image

4. **Click save and its done.**

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

- [x] I am a GSSoC'24 contributor
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

@Yeasir0032 Please review this PR. After merging the PR, don't forget to add `gssoc24` ,`level` labels and assign this PR to me, otherwise my points won't be added.
Thanks

### CODE REVIEW

**Comment by PayalKumari10** [comment]
Tell me, @harmeetsingh11  what exactly this workflow does. Why did you create it?

**Comment by harmeetsingh11** [comment]
@PayalKumari10 This workflow uses CodeQL, GitHub's code analysis engine, to automate security checks in a `TypeScript` repository by scanning for vulnerabilities and presenting findings as code scanning alerts. 

It will be triggered by every push, commit, and pull request, the workflow continuously monitors the codebase to maintain high security and quality standards. It was created to proactively identify and flag potential security issues, particularly in environments with frequent code changes, thereby preventing the introduction of vulnerabilities and ensuring a robust and secure application.

**Comment by PayalKumari10** [comment]
Thank you for the explanation, @harmeetsingh11. This CodeQL workflow for automated security checks in our TypeScript repository sounds great. It will help us maintain high security and quality standards by continuously monitoring for vulnerabilities.

**Comment by harmeetsingh11** [comment]
@Yeasir0032 please add `gssoc` and `level` labels to the PR, otherwise my points won't be added.

**Pull request merged**
