### PR TITLE
Fix issue 30: Update README

### PR DESCRIPTION
**Pull request by jinx-vi-0**
This pr addresses Issue #30 by updating the README file to reflect the latest changes and provide clear instructions for users.

### CODE REVIEW

**Comment by Yeasir0032** [comment]
How can see the Preview?

**Comment by jinx-vi-0** [comment]
> How can I see the Preview?

@Yeasir0032 , I exactly don't know how to do that, but you can do one thing. create a branch in your repo and merge the pr to that branch and after preview merge it to your main branch.

or I can provide ss to preview.

**Comment by Yeasir0032** [comment]
Please provide a screenshot

**Comment by jinx-vi-0** [comment]
@Yeasir0032 

image
image
image
image

**Pull request merged**
