### PR TITLE
remove close icon

### PR DESCRIPTION
**Pull request by Varsani2520**
i removed the closed icon on the homepage dialog box model

### CODE REVIEW

**Comment by Varsani2520** [comment]
@Yeasir0032 

if you merge my pr, than why i can;t find my name in contribution list

**Comment by Yeasir0032** [comment]
@Varsani2520 
I don't know exactly the reason of this but it might be due to not referencing issue in the PR.

**Comment by Yeasir0032** [comment]
Try  referencing the issue in this pr

**Comment by Varsani2520** [comment]
@Yeasir0032 i update my pr with issue no please check and close #38

**Pull request merged**
