### PR TITLE
Added the feature to auto comment on pull request being raised 

### LINKED ISSUE #71: Auto commenting feature for new PR raised
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
## Related Issue
Fixes #71 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Yeasir0032 — COMMENTED** [review]
Is not this works the same way for this [Workflow](https://github.com/Yeasir0032/Discord-Clone/blob/main/.github/workflows/greetings.yaml)

**Comment by suhanipaliwal** [comment]
> Is not this works the same way for this [Workflow](https://github.com/Yeasir0032/Discord-Clone/blob/main/.github/workflows/greetings.yaml)

This workflow only comments when a contributor raises a pr for the first time but my workflow comments on every pr raised.

**Comment by suhanipaliwal** [comment]
Please assign me this pull request and add the labels of gssoc and appropriate level on this issue as per new gssoc guidelines.

**Comment by Yeasir0032** [comment]
@suhanipaliwal 
Thank you for pointing out

**Pull request merged**
