### PR TITLE
#18 Creating a explore page for servers

### LINKED ISSUE #18: Creating a explore page for servers
### Server Explorer
A **new user** who has not been in any server can go to this page and find and join a server.

**Current scenario:**- 
Whenever a new user is created , a server create modal appears.

**Solution:**
The new user will be redirected to the server explorer page and can select and join any server.

**Overview of the solution:**
- Create a new route in app directory
- Create page.tsx file
- Get all servers from database
- Display them 
- Handle searching and joining

### PR DESCRIPTION
**Pull request by Latish705**
closes #18 added new backend  route for getting all the servers and frontend route to explore all the servers

### CODE REVIEW

**Comment by Latish705** [comment]
@Yeasir0032 anything more we need to do

**Comment by Yeasir0032** [comment]
Is everything working fine?
The image problem?

**Comment by Yeasir0032** [comment]
Hey @Latish705 , Did you fix the image problem

**Comment by Yeasir0032** [comment]
Okay I will do that 
@Latish705 
Grant me push access in your forked repo.

**Comment by Latish705** [comment]
@Yeasir0032 there was no issue with image the problem was I could able to test with database as could write to database that testing is remaining 
I would suggest you to add your database and see

**Comment by Yeasir0032** [comment]
@Latish705 
I have changed some more and rectified some mistakes. I have added a commit.
Please give write access to your forked repo so that I can change the PR

**Comment by Latish705** [comment]
image
already given

**Comment by Latish705** [comment]
@Yeasir0032 what happen with this pr?

**Pull request merged**
